//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaberColorfulStartmenu.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaberColorfulStartmenu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Saber&apos;s Colorful Startmenu Version:2.2 (release 2.2)
        ///
        ///作者：HV0905
        ///
        ///仅支持Win10操作系统
        ///
        ///本程序可以通过修改快捷方式文件下的visualelementsmanifest.xml对开始菜单图标进行定制
        ///
        ///本程序部分图标取自 Windows 9 Icons 作者: dtafalonso
        ///参考: dtafalonso.deviantart.com/art/Windows-9-icons-359505915
        ///
        ///背景：取自b站，如果你知道原作者可以在github反馈。
        ///
        ///基于C# WPF .Net Framework 4.6.2 使用Visual Studio 2017 Community编译
        ///
        ///本程序开放源代码,任何人可以免费散布/重新编译本程序,如需下载源代码，请前往Github页面。 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saber&apos;s Colorful Startmenu 的本地化字符串。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 __StartmenuIcons__ 的本地化字符串。
        /// </summary>
        internal static string IconDirName {
            get {
                return ResourceManager.GetString("IconDirName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Magnify,放大镜
        ///Notepad,记事本
        ///Narrator,讲述人
        ///On-Screen Keyboard,屏幕键盘
        ///Command Prompt,命令提示符
        ///Speech Recognition,语音识别
        ///Math Input Panel,数学输入面板
        ///Paint,画图
        ///Quick Assist,快速助手
        ///Remote Desktop Connection,远程桌面连接
        ///Snipping Tool,截图工具
        ///Steps Recorder,步骤记录器
        ///Wordpad,写字板
        ///XPS Viewer,XPS查看器
        ///dfrgui,碎片整理和优化驱动器
        ///Disk Cleanup,磁盘清理
        ///IIS Manager,IIS管理器
        ///iSCSI Initiator,iSCSI发起程序
        ///Memory Diagnostics,Windows内存诊断
        ///ODBC Data Sources (32-bits),ODBC数据源 （32位）
        ///ODBC Data Sources (64-bits),ODBC数据源 （64位）
        ///RecoveryDrive,恢复驱动器
        ///Resource Monit [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SysCharMap_CN {
            get {
                return ResourceManager.GetString("SysCharMap_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon 龙_飞车 {
            get {
                object obj = ResourceManager.GetObject("龙_飞车", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
